service: express-serverless-boilerplate


provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
  environment:
    NODE_ENV: production
    basePath: dev/
  cfLogs: true

functions:
  hello:
    handler: lambda.handler
    events:
      - http:
         path: index
         method: get
         integration: lambda-proxy
      - http:
         path: users
         method: get
         integration: lambda-proxy
